### ISSUE TITLE
Pause when fullscreen

### ISSUE THREAD

**Issue by dimqua** [ltGuillaume/Redshift-Tray#1]
Would be nice to have a possibility to pause the redshift when user open any full-screen window.

Not sure if it's possible, but FYI this feature exist in LightBulb.

**Comment by ltguillaume** [comment]
@dimqua Please try [rstray_1.4.0TEST.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1423472/rstray_1.4.0TEST.zip), go into settings and change "disableonfullscreen" from 0 to 1.

**Comment by dimqua** [comment]
@ltGuillaume does not work for me. I created the option manually, since it doesn't exist in config by default.

**Comment by ltguillaume** [comment]
It wil exist when you open the settings from within Redshift Tray. What program in full-screen mode did you test it with? I tried PotPlayer and IrfanView, both work perfectly fine. I disabled it for Windows' Remote Desktop Client.

**Comment by dimqua** [comment]
>It wil exist when you open the settings from within Redshift Tray

Yes, but not instantly, I need to wait for a minute to be able to see this option. That's why I thought it was not exist.

UPD. It works! Thanks!

**Comment by dimqua** [comment]
Do not work with IrfanView too, in my case.

**Comment by ltguillaume** [comment]
@dimqua What happened? Did you miss it due to the slow fading into the shifted color temperature or something? It's easier to test it when Forced mode is on.

>Yes, but not instantly, I need to wait for a minute to be able to see this option. That's why I thought it was not exist.

It should. I guess you were still running the old version, or you already had the .ini file opened manually? As soon as you hit "Settings", Redshift Tray recreates all the options it has (with default values if they're not changed), including the new option.

**Comment by dimqua** [comment]
Probably, I forgot to restart the program after I change the option.
>you already had the .ini file opened manually

Yes, and this too.

> the slow fading into the shifted color temperature 

IMHO, should be an option to specify fading time. Since it's too slow, indeed. I mean, a lot of advanced options are present, but it's a basic feature.

**Comment by ltguillaume** [comment]
Does Redshift allow this? And I think it's such a minor issue that it hardly matters. And the Force mode is there for that reason, too, amongst others.

**Comment by dimqua** [comment]
Oops, no. But it's possible to [disable the smooth fade](https://github.com/jonls/redshift/blob/b210813c7ffdd0eae75eb60c7bbbb62b6b109ebe/redshift.conf.sample#L7).

**Comment by dimqua** [comment]
I used [LightBulb](https://github.com/Tyrrrz/LightBulb) previously and thought that Redshift allows this too. But I agree, it's a kind of minor issue.

**Comment by ltguillaume** [comment]
> Oops, no. But it's possible to disable the smooth fade.

Ah, that feature has been added on August 31. Since there's no official release / Windows binary yet, I'd have to recompile Redshift myself, which means setting up a new gcc environment in a VM again (I lost the previous machine). To be honest, I think I'm gonna pass all that for a mere x second delay.

**Comment by dimqua** [comment]
You can use the latest snapshot, if you wish: https://github.com/jonls/redshift#latest-builds-from-master-branch

**Comment by ltguillaume** [comment]
Thanks. I just saw that isn't necessary: they simply renamed the feature. I've implemented a "notransitions" option. Check the [releases page](https://github.com/ltGuillaume/Redshift-Tray/releases/).

**Comment by ltguillaume** [comment]
@dimqua Please re-download the fixed v1.4.0 from the [releases page](https://github.com/ltGuillaume/Redshift-Tray/releases/). I'd say it now works exactly as you mean (no matter if notransitions=1 or 0, it'll quickly pop back on after leaving full-screen). There also was an issue where going to the Windows desktop would pause Redshift.

**Comment by ltguillaume** [comment]
@dimqua Created a full-screen mode with separate color temperature for full-screen windows (just set to 6500 to pause, like before).
