### ISSUE TITLE
Browsers blocking download due to malware / virus warning.

### ISSUE THREAD

**Issue by mattez** [ltGuillaume/Redshift-Tray#10]
**Windows 10 Pro**
**Chrome** 71.0.3578.98 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/143115/51417562-37ab0300-1b87-11e9-866e-9206aea8ab0e.png)

**Firefox** 64.0.2 (64-bit)
![image](https://user-images.githubusercontent.com/143115/51417603-688b3800-1b87-11e9-83ab-f6aebc1a0a1f.png)

**Comment by ltguillaume** [comment]
Hi. Yeah, unfortunately AutoHotkey is oftentimes recognized as a virus, even though there's nothing going on. I've uploaded v1.8.1, which - according to Jotti's malware scan - is only considered suspicious by VBA32.
