### ISSUE TITLE
Redshift Tray on Chocolatey is outdated

### ISSUE THREAD

**Issue by ltguillaume** [ltGuillaume/Redshift-Tray#14]
@dimqua Would you please be so kind to update the package, as it's still stuck at v1.9.3?

**Comment by ltguillaume** [comment]
I have contacted the Chocolatey administrators quite some time ago, but there's still no response. I wasn't a fan of Chocolatey anyway (its documentation is ridiculous and the "framework" is needlessly complex), but this is just begging for unmaintained repos.

**Comment by pauby** [comment]
The packages on the Chocolatey Community Repository are maintained by volunteer maintainers and vendors / authors. The Chocolatey Administrators / Team don't maintain packages.

There is a [package triage process](https://chocolatey.org/docs/package-triage-process) that should be followed when packages are out of date, unmaintained or 'broken'. In the firs instance you should try contacting the maintainers using the 'Contact Maintainers' link on the package page and waiting at least 7 days for a response. If no response is received you can either:

* If you want to become a maintainer of the package, click the 'Contact Site Admins' link on the package page to request it;
* If you don't want to become a maintainer of the package, raise an issue over at https://github.com/chocolatey/chocolatey-package-requests/issues;

Hope that helps.

**Comment by ltguillaume** [comment]
I know, I went through it twice, but only the last time I got a reply: apparently the emails weren't sent to the Chocolatey admins during the period I sent in the request.

But they just said that I should try to contact @dimqua again, so no real help there.

I honestly don't like Chocolatey at all, so I don't have any aspirations to be the package maintainer either, but as long as my project is on there, it should at least be up-to-date.

**Comment by pauby** [comment]
> But they just said that I should try to contact @dimqua again, so no real help there

Did you do that via the method that they / I suggested?

> I honestly don't like Chocolatey at all

I got that from your previous message.

>  so I don't have any aspirations to be the package maintainer either, but as long as my project is on there, it should at least be up-to-date.

Agreed. That's why I provided the second link if you had contacted the maintainer via the recommended method.

**Comment by ltguillaume** [comment]
Ah wait, you're the same person who responded to my message to Chocolatey 🙂 I suspected it before, decided to finally check on that 😉

> Did you do that via the method that they / I suggested?

Yeah, did that, but I might as well try again right now.

>> I honestly don't like Chocolatey at all

> I got that from your previous message.

Sry, didn't want to sound impolite (if I did). Even though I see the appeal to bring a package manager to Windows (even Microsoft themselves do, with the latest news of their as of yet botched implementation for it), but when I went through the documentation (multiple times, but about 6 months ago already tbh) I found it rather unclear, plus the folder structure is counterintuitive (considering permissions etc.), especially when applied to a simple portable program such as this one. Stuff might have improved a lot since I last checked, though.

Cheers!

**Comment by pauby** [comment]
> Yeah, did that, but I might as well try again right now.

If you've already done that and had no reply then I'd move onto raising an issue at https://github.com/chocolatey/chocolatey-package-requests/issues. The emails that were 'not working' were only to Site Admins for a short period of time. The maintainer emails were still being sent as normal.

> Sry, didn't want to sound impolite (if I did). Even though I see the appeal to bring a package manager to Windows (even Microsoft themselves do, with the latest news of their as of yet botched implementation for it), but when I went through the documentation (multiple times, but about 6 months ago already tbh) I found it rather unclear, 

This isn't the best place for this but I am curious about what wasn't unclear / what you had difficulty with etc.?

> plus the folder structure is counterintuitive (considering permissions etc.), 

Can you elaborate on that?

> especially when applied to a simple portable program such as this one. 

If your installing Chocolatey to just install Redshift Tray then it's a bit overkill, I agree. But what it does mean is that everytime there is an update to the software a simple `choco up all` updates all of the software on your machine (including this). So it allows your system to be fully up to date, software wise, with one simple command. I personally have to have a REALLY good reason to install software outside of a Chocolatey package these days. It's just not worth the hassle. I want one place, update the software with one command and that's it.

That does assume of course that the package / maintainer is up to date.

> Stuff might have improved a lot since I last checked, though.

It's a case of what works for you. If what you are doing right now works for you, keep doing it. If you want to try something else then give Chocolatey a go. And then if you still feel it doesn't work for you then go back to your previous process. The most important thing is keeping your software up to date the way that works _for you_.

**Comment by pauby** [comment]
I am happy to take this 'offline' so as not to mess up this issue any further but I wanted to address your concerns initially.

**Comment by ltguillaume** [comment]
> I am happy to take this 'offline' so as not to mess up this issue any further but I wanted to address your concerns initially.

No, don't worry, I don't mind at all.

> This isn't the best place for this but I am curious about what wasn't unclear / what you had difficulty with etc.?

I don't remember exactly anymore, so please bear with me, but I believe two things were difficult to understand:

1. The rstray.exe file needs to write to its own folder, like most portable tools, and the first versions of the packages by @dimqua therefore couldn't save their .ini files. How the per-folder permissions in the whole structure are in Chocolatey wasn't described properly (back then).
2. RSTray is dependent on redshift.exe, which is also a package here, and @dimqua wanted to solve this with a dependency, rather than using another instance of redshift.exe (possibly risking conflicts?).

That's what I remember at least, but I haven't checked the current situation.

> If your installing Chocolatey to just install Redshift Tray then it's a bit overkill, I agree.

No, what I meant was from a developer's, or rather from the package manager's point of view. So how to package such a simple program with Chocolatey, a program that needs to be able to write to its program directory?

**Comment by ltguillaume** [comment]
@pauby I have sent @dimqua a message via "Contact maintainers" 12 days ago. No response, again.

**Comment by pauby** [comment]
> The rstray.exe file needs to write to its own folder, like most portable tools, and the first versions of the packages by @dimqua therefore couldn't save their .ini files. How the per-folder permissions in the whole structure are in Chocolatey wasn't described properly (back then).

You can effectively put files anywhere with a Chocolatey package. Whether that will pass moderation for the Chocolatey Community Repository or not is a different question (remember Chocolatey != Chocolatey Community Repository). There are of course best practices and recommendations. When working with portable packages you need a place where files (like the .ini files you mention) can be saved to _without_ administrator permissions (which is the hallmark of portable tools). Chocolatey typically uses the `c:\tools\` folder with a `<packagename>` folder underneath there. You can use the [`Get-ToolsLocation`](https://chocolatey.org/docs/helpers-get-tools-location) function or the `ChocolateyToolsLocation` environment variable to get the default location in your Chocolatey scripts (there are [many more functions and variables too](https://chocolatey.org/docs/HelpersReference)).

So long story short on that, you'd likely install the portable tool into `c:\tools\rstray`.

> RSTray is dependent on redshift.exe, which is also a package here, and @dimqua wanted to solve this with a dependency, rather than using another instance of redshift.exe (possibly risking conflicts?).

There are two answers to this:

1. It should really be done with a dependency;
2. In the real world using a dependency might not work as we expect;

Dependencies allow us to cut down on the amount you bundle in a package. .NET is the classic example of this. So much software needs it and if they all bundled it into the package they would be huge, the downloads would be huge, wasteful and time consuming. So separate packages are created - one for the application and one for .NET.

So given what I said above, and given the little I know about the requirements here I'd move towards suggesting that a separate package is the best way to go.

> No, what I meant was from a developer's, or rather from the package manager's point of view. So how to package such a simple program with Chocolatey, a program that needs to be able to write to its program directory?

See above 😄 Does that explain it?

(apologies for the delay in responding).

**Comment by ltguillaume** [comment]
Thanks for the reply! That makes sense. In this case the "dependency" is just a single file, redshift.exe. I don't think that warrants a dependency setup, especially since Redshift itself is rarely updated. What's more, I believe the problem with earlier versions of @dimqua's package was that since rstray.exe needs redshift.exe in the same folder, rstray.exe was extracted into C:\tools, just like (back then at least) redshift.exe via its separate package. The problem was that rstray.ini could not be written to in this case due to the folder permissions. This was quite a while back, things may have changed since. Either way, a separate folder C:\tools\rstray makes sense.

**Comment by pauby** [comment]
A quick clarification - does redshift.exe HAVE to be in the same folder as rstray or can it be on the path?

If, as you say, redshift.exe and rstray need to be in the same folder then putting them into separate packages won't work (as they'd then be in separate folders). So I agree that putting them into the same package makes sense. The only issue will be that you then have two 'software' to keep track of - if redshift.exe is updated then the package should be updated and is rstray is updated then the package needs to be updated. And then you have the issue of which version do you use - rstray or redshift.

Let's say you version it on rstray and redshift.exe is updated, how do you bump the version number? And then when you do the package version doesn't match the rstray version (which, when using the Chocolatey Community Repository it should _where practical_). I know you said redshift.exe doesn't get updated often, but it does get updated so you will come across this issue.

So these are things to think about. But these are not limitations because of Chocolatey. These are just generic 'package manager' limitations / caveats.

I am actually thinking maybe I will pick this package up just to because of what we have discussed. I don't have any use for it (I use the Windows 10 built-in night mode) but I do also maintain the [f.lux](https://chocolatey.org/packages/f.lux) packages (.install and .portable - the portable one has it's own installer however so it's not really comparable to this).

**Comment by AdmiringWorm** [comment]
> A quick clarification - does redshift.exe HAVE to be in the same folder as rstray or can it be on the path?

In theory, even if redshift.exe needs to be in the same directory as rstray it could be a separate package.
During the installation of the rstray package, a symlink could perhaps be created to the redshift.exe executable (assuming rstray don't make a distinction between a symlink and the actual executable).

**Comment by pauby** [comment]
@AdmiringWorm I thought about that and came to the conclusion it was just going to be too much of a PITA to maintain. Just my thoughts though.

**Comment by ltguillaume** [comment]
I obviously could change rstray so that it could run redshift.exe from the path env. variable, but I was just describing the two things that went wrong back then. Redshift for Windows hasn't changed since 2018 (apart from a single change that only matters when compiling), plus I'm using a slightly modded version of redshift anyway (mostly cosmetic and with debug symbols stripped), so packaging redshift.exe (with its whopping 93KB) is preferable anyway.

**Comment by ltguillaume** [comment]
@tunisiano187 Thanks for updating the Chocolatey package so quickly. Unfortunately, the binary I uploaded didn't contain a last change. I updated it a little bit later. Since the package is still under review, perhaps you could update rstray.exe with the latest version beforehand. The change doesn't affect functionality, it only reduces CPU use a bit.

**Comment by tunisiano187** [comment]
I'll check this tommorow asap

**Comment by ltguillaume** [comment]
Thanks!

**Comment by ltguillaume** [comment]
All good now?

**Comment by tunisiano187** [comment]
Hello,
Sorry i forgot it.
It has been update now.
Have a nice day

**Comment by ltguillaume** [comment]
Thanks!!

**Comment by ltguillaume** [comment]
Pinging @tunisiano187 about https://github.com/ltGuillaume/Redshift-Tray/releases/tag/2.1.0 😉
