### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by tunisiano187** [ltGuillaume/Redshift-Tray#15]
Hello,
i have received a message from a chocolatey user about a malware detection from Windows defender, can you tell me more about it?
Thank you

Hi latest update v1.9.9 gives a Windows Defender warning:
Trojan:Win32/Zpevdo.B
file: C:\WINDOWS\System32\Tasks\Redshift Tray->(UTF-16LE)
regkey: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tasks\{A1341D6B-CE51-451B-B970-C4CB9CA6736F}
regkey: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\TaskCache\Tree\Redshift Tray
taskscheduler: C:\WINDOWS\System32\Tasks\Redshift Tray

**Comment by ltguillaume** [comment]
See the comment at the top of the releases. These are all false positives and a well-known byproduct of the AutoHotkey interpreter. The executable is nothing more than the exact script as committed to GitHub (you can see the plain text inside rstray.exe using any text editor) run through AutoHotkey's ahk2exe.exe.
