### ISSUE TITLE
Flagged on virustotal

### ISSUE THREAD

**Issue by tunisiano187** [ltGuillaume/Redshift-Tray#19]
Hello Guillaume,
The package on chocolatey is flagged in virustotal, so it doesn't pass the validation, any idea why ?
https://github.com/tunisiano187/Chocolatey-packages/issues/3007

**Comment by ltguillaume** [comment]
Please check _all_ the other closed issues about this... There's also a statement in every release text...

**Comment by tunisiano187** [comment]
Ok,thank you, i'll send it to the moderators
