### ISSUE TITLE
Disable on fullscreen Bug

### ISSUE THREAD

**Issue by dimqua** [ltGuillaume/Redshift-Tray#2]
There is a bug when disableonfullscreen=1. Steps to reproduce it:
- Mouse click on desktop wallpaper.
- Wow! Redshift-Tray is disabled.

**Comment by ltguillaume** [comment]
Are you on Windows 7 by any chance?

**Comment by dimqua** [comment]
Windows 10 Enterprise 2016 LTSB

**Comment by ltguillaume** [comment]
Hmz, I can't reproduce (W10 here). I had that before, but it's fixed for me. Please be sure you have the absolute latest version (I've been silently updating v1.4.0 for a while). Do you have a "Help" item in the tray menu? Of not, please download and try again.

**Comment by dimqua** [comment]
>Do you have a "Help" item in the tray menu?

Yes.
Probably, it's a LTSB-related issue, since this version does not update as often as non-LTSB versions.

BTW, I added your program to chocolatey repository (the package is not approved yet).
https://chocolatey.org/packages/redshift_tray/

**Comment by ltguillaume** [comment]
Maybe it's Aero-related. Have a look at [v1.4.1](https://github.com/ltGuillaume/Redshift-Tray/releases/)

**Comment by ltguillaume** [comment]
Chocolatey is cool.

**Comment by dimqua** [comment]
Now it works as excepted! Thanks again.

**Comment by ltguillaume** [comment]
Yesss. nice!

**Comment by ltguillaume** [comment]
> BTW, I added your program to chocolatey repository (the package is not approved yet).
https://chocolatey.org/packages/redshift_tray/

Guess that didn't work out as planned :-P

**Comment by dimqua** [comment]
https://chocolatey.org/packages/rstray/

**Comment by ltguillaume** [comment]
Cool!
