### ISSUE TITLE
Allow to choose nighttemp and daytemp times artificially

### ISSUE THREAD

**Issue by karolzlot** [ltGuillaume/Redshift-Tray#22]
I see this option:
>If you want total control over the times at which Redshift will be enabled and disabled, just set nighttime=1800 and daytime=0600, where the values depict 24h military time. Then, set customtimes=1.

I would like to achieve something similar, but instead of "disabled" and "enabled" I want to control when nighttemp and daytemp are applied.

I don't want it to be controlled by latitude and longitude.

How can I achieve it?

**Comment by ltguillaume** [comment]
You have found the right options for that in your quote. So right-click the tray icon, choose Settings > More settings and edit those three values in the ini-file that opens. Save and close the file and rstray will restart using your custom times.

**Comment by karolzlot** [comment]
@ltGuillaume It doesn't work, because when redshift is disabled, then `daytemp` isn't applied. 

It works like this:
nighttime -> nightemp
daytime -> disabled (daytemp is not applied)

I would like to have for example 3400K for nighttemp and 4400K for daytemp.

**Comment by karolzlot** [comment]
I mean, I tried to do this in this ini file and those are my results.

**Comment by ltguillaume** [comment]
Aaah sorry, I seem to have misread your first post. Indeed, custom times didn't apply the daytemp during the day. Thanks for reporting this! I fixed it in [v2.2.3](https://github.com/ltGuillaume/Redshift-Tray/releases/tag/2.2.3).

**Comment by karolzlot** [comment]
Thanks!
