### ISSUE TITLE
Feature suggestion: Custom on/off time

### ISSUE THREAD

**Issue by dimqua** [ltGuillaume/Redshift-Tray#3]
If you I wish to add something new to the next versions, you may want to add this feature.

This is the [SunsetScreen program](http://www.skytopia.com/software/sunsetscreen/) author's explanation:

>Programs such as F.lux partially solve the problem, but in the winter, I found the sunsets came too early. This caused F.lux to darken the screen early too. Just because it's dark outside early, that does not mean the human body clock revolves around the winter's schedule. Many, perhaps most people find considerable benefit to extra light during the day during the darker seasons, and if this extends to your laptop, tablet or computer screen, then we should allow that!

>Morning larks, night owls and even those who work night shifts will benefit from using SunsetScreen because their sleep cycles are hours apart from each other. SunsetScreen can be tailored so you can set the sunset and sunrise times appropriately to match your sleep rhythm.

>We should also be able to define the colour of the filter by hue, saturation or brightness if need be. This way, we can match the colour more precisely to the illumination by the light bulbs we have in our houses. Although dimming the amount of blue light is most important, the overall brightness may also be dimmed too if you so wish.

**Comment by ltguillaume** [comment]
Hmz, I'll think about it.

**Comment by ltguillaume** [comment]
@dimqua Are you still using it? Then I'll implement it.

**Comment by dimqua** [comment]
Yes.

I noticied that you removed "disableonfullscreen" option, but didn't mention this in the changelog.

**Comment by ltguillaume** [comment]
In v1.4.2:
- [x] Replaced "disable on full-screen" feature with "full-screen mode": set a different color temperature for full-screen windows

So if you set fullscreen temp to 6500K, it does the same asdisableonfullscreen.

**Comment by ltguillaume** [comment]
@dimqua Please have a look at this version. Just go to More settings... and set the two parameters, e.g. 
```
nighttime_HHmm=1700
daytime_HHmm=0600
```
[redshift_1.5.1test.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1514753/redshift_1.5.1test.zip)
(Don't test by setting the daytime _after_ the nighttime, that won't work: the daytime needs to be in the morning, the nighttime in the afternoon/night)

**Comment by dimqua** [comment]
@ltGuillaume It works for me.

> (Don't test by setting the daytime after the nighttime, that won't work: the daytime needs to be in the morning, the nighttime in the afternoon/night)

Can I set ```daytime_HHmm=0001``` and ```nighttime_HHmm=2359```, for example?

**Comment by ltGuillaume** [comment]
Should work, good to test!

**Comment by ltGuillaume** [comment]
Wait, it won't! Haha, hang on!

**Comment by ltGuillaume** [comment]
@dimqua but this one should.
[redshift_1.5.1test.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1514855/redshift_1.5.1test.zip)

**Comment by ltGuillaume** [comment]
@dimqua All ok?

**Comment by ltGuillaume** [comment]
I'm rewriting this shit and I'm tired and please bear with me.

**Comment by ltGuillaume** [comment]
Almost there

**Comment by ltGuillaume** [comment]
@dimqua Please have a look at this one. Careful, it uses a new .ini file structure, so you'll need to move around your settings after the first run.
[rstray.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1537302/rstray.zip)

**Comment by ltguillaume** [comment]
@dimqua Please try this one. Beware that your settings will be semi-lost: I restructured the .ini file, so either move the toggle options from [Redshift] to [Toggles] and the value options to [Values] or start with a fresh .ini file.
See next post.

**Comment by ltGuillaume** [comment]
Updated: [rstray.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1537485/rstray.zip)

**Comment by ltGuillaume** [comment]
Updated: 
[rstray.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1537497/rstray.zip)

**Comment by ltguillaume** [comment]
Updated (3rd time by now, sjeesh):
[rstray.zip](https://github.com/ltGuillaume/Redshift-Tray/files/1537506/rstray.zip)

**Comment by dimqua** [comment]
Works for me, the daytime should be earlier then the nighttime, but it's fine.

Can I suggest to add "Disabled until hh:mm (6500K)" tooltip? Where hh:mm is nighttime, obviously.

**Comment by ltguillaume** [comment]
Should do that, see https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.6.0

**Comment by ltguillaume** [comment]
@dimqua Oh and [Toggles] has been renamed to [Switches], so that needs to be changed in your current .ini, sorry.
