### ISSUE TITLE
Switch between open items works even if optionalhotkeys=0

### ISSUE THREAD

**Issue by maximd** [ltGuillaume/Redshift-Tray#4]
Hi,

Even with redshift-tray launched with `rstray.ini` containing:

```
optionalhotkeys=0
```

The "Switch between open items" hotkeys mapped to `AltGr .` and `AltGr ,` are still active.

**Comment by ltguillaume** [comment]
Strange stuff! Do you by any chance have `Remote Desktop support` enabled? If so, what happens if you turn it off?

**Comment by ltguillaume** [comment]
Hmz, just came home and tested. Behavior confirmed, will investigate further.

**Comment by ltguillaume** [comment]
Ok, done: https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.6.4
