### ISSUE TITLE
Feature request: disable all hotkeys

### ISSUE THREAD

**Issue by maximd** [ltGuillaume/Redshift-Tray#5]
Hi,

It would be really nice to be able to disable hotkeys completely (not just advanced hotkeys) because some shortcuts conflict with software that we use.

**Comment by ltguillaume** [comment]
Which software is it? If they aren't global hotkeys (i.e. able to be triggered from outside the software you're using), I can add their window class name to prevent Redshift Tray from interefering. If it's proprietary software, you can run `WindowSpy.ahk` that's included in the [AutoHotkey package](https://www.autohotkey.com/download/) and pass on the class name(s) yourself.

**Comment by ltguillaume** [comment]
Ok, done: https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.6.4

**Comment by maximd** [comment]
I don't have the detail: a friend of mine told me about the problem but he was a using a 3D software (which are full of hotkeys :smile:).

In any case thanks a lot for your work!

**Comment by ltguillaume** [comment]
No worries! If your friend ever needs the hotkeys outside of that software,
just let me know!

**Comment by ltGuillaume** [comment]
Small update for Redshift Tray, big update for Redshift: https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.6.5

**Comment by ltguillaume** [comment]
@maximd Small update for Redshift Tray, big update for Redshift: https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.6.5hp

**Comment by ltguillaume** [comment]
@maximd Just so you know, v1.6.5 caused some issues when using Forced mode or increasing/decreasing brightness. Fixed in 1.6.6.

**Comment by maximd** [comment]
Ok, thanks for the feedback!
