### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by dimqua** [ltGuillaume/Redshift-Tray#6]
Can you please add a possibility to hide tray icon of the program?

**Comment by ltguillaume** [comment]
To be honest, I don't think that would be wise: the tray icon is the only
UI element of the program, and as such the only way of closing / restarting
it. Tray icons can easily be removed from sight by Windows' internal
feature to hide tray icons. Anybreason why that doesn't suffice for your
use case?

**Comment by dimqua** [comment]
I just want to save the space in tray. By hiding single icon this can't be achieved, since it can't be **completely** hidden by Windows. And I don't need to close/restart the program usually or see it's status.

>I don't think that would be wise: the tray icon is the only UI element of the program

Of course, it should only be placed in advanced settings (as rstray.ini switch).

**Comment by ltguillaume** [comment]
So... You're worried about 1 triangular "tray icon overflow" button?

**Comment by ltguillaume** [comment]
This is just the .ahk file that shouldn't show any tray icon. Just put it in the folder with rstray.ini and redshift.exe. You can run it by downloading [AutoHotkey](www.autohotkey.com) and associating `autohotkeya32.exe` to .ahk files.
[rstray.ahk.zip](https://github.com/ltGuillaume/Redshift-Tray/files/2271932/rstray.ahk.zip)

**Comment by dimqua** [comment]
Thanks!
> the only way of closing / restarting it

I think it's possible to use hotkeys for enabling/disabling redshift.

**Comment by ltguillaume** [comment]
Yeah, that's true, but I meant Redshift Tray with "the program", not Redshift. Sometimes AutoHotkey loses the keyboard hook (so hotkeys don't work anymore) and the easiest way to get it in order again is to restart the script (in this case Redshift Tray). That's why there's a "Restart" option via the tray menu. But in your case, it should suffice if you just open the .ahk again.
