### ISSUE TITLE
Redshift Tray 1.7.0

### ISSUE THREAD

**Issue by smaragdus** [ltGuillaume/Redshift-Tray#8]
I had [Redshift Tray](https://github.com/ltGuillaume/Redshift-Tray) [version](https://github.com/ltGuillaume/Redshift-Tray/releases/) [1.7.0](https://github.com/ltGuillaume/Redshift-Tray/releases/tag/1.7.0) (from _2018-08-12_) and by chance I discovered that there was a newer **1.7.0** version (from **2018-08-13**), hashes:

- **Redshift Tray 1.7.0** (from _2018-08-12_)
```
Name: redshift-tray_1.7.0.zip
File Size: 579356 Byte(s) (565.78 KB)
Modified Date: 2018-08-12 19:13
MD5: c853e79d96c7440743a02a00ff5d6827
SHA1: 54cf4837d5c7252b951feb8e37e10173a5691907
SHA256: 585955a0b1c24f120f2b734700cf861247c06c19a92dbc90342d5783a533ab67
SHA384: 65079d31e7189dd007240dbac9ab1fbfceeebc6a8f084c03bb4e57cadcc551c883df1e9cd626a9563ce4f0152be3fe8a
SHA512: 7a5afd9da0acc1e81104ce6caebffb0bfc284b11922aa75c0a5538f2a043e37e291d608cd4a6ab2d6a6bd243566c43df0789e13d5d7b3ad58f54f82ff7b0f08e
 ```
 - **Redshift Tray 1.7.0** (from _2018-08-13_)
```
Name: redshift-tray_1.7.0.zip
File Size: 514175 Byte(s) (502.12 KB)
Modified Date: 2018-08-13 13:02
MD5: 782d34f73a5192c4bc516821b7ffe671
SHA1: cf4752f6ebb8f86f026446a6628fe46d996c1d11
SHA256: 1a2d389c563bf155b74e8f017fcc1fe6cbe525256bfc117dc1652d0522d02141
SHA384: f69420908fca2ba773e9e4ca2df992064631764f9cae5fd39708430cb599af0c584f0576f8880ddc48afba09505e01e0
SHA512: b7b42d61d22b1391e295bed68c156860918fd095fede14061a92877d367ad038302d87787809441da4caa545bc6d5e75e8c5c01afd5953846ef901811780ce1d
```
The different file is **redshift.exe**.

In my opinion replacing once uploaded versions without raising the version number is a bad practice- the users cannot be sure whether they are using the latest version.

**Comment by ltguillaume** [comment]
Fair enough, but the only thing I did was replace the icon inside (which merely shows in the Task Manager anyway, not the tray). There were no functional differences between these versions, only cosmetical. I didn't think I should bother any of the users with that kind of perfectionism from my side. That being said, I will make sure to not do any silent updates anymore.

**Comment by smaragdus** [comment]
@ltGuillaume 

No real grudges here- the program is excellent, I like it and use it daily. It just happened that I noticed a different (newer) version than mine.

Keep the good work and happy holidays.

Regards

**Comment by ltguillaume** [comment]
Thanks, glad to hear that!

Happy holidays to you, too!
